parts/iivari/server/config/routes.rb
Iivari::Application.routes.draw do
  resources :school_admin_groups, :path => ':school_id/admins' do
    collection do
      put(':group_id',
          :to => 'school_admin_groups#add_group',
          :as => 'add_group' )
      delete(':group_id',
          :to => 'school_admin_groups#delete_group',
          :as => 'delete_group' )
    end
  end
  resources :displays, :path => ':school_id/displays'

  match '/channels/welcome', :to => "channels#welcome", :as => 'welcome'
  resources :channels, :path => ':school_id/channels' do
    resources :slides do
      post :sort, :on => :collection
      member do
        put :toggle_status
        get :slide_status
      end
    end
  end

  resources :slides, :path => ':school_id/slides' do
    resources :slide_timers
  end

  match '/slides/new/:template', :to => "slides#new", :as => 'template_new_slide'

  match 'conductor', :to => "screen#conductor", :as => "conductor_screen"
  match 'slides.json', :to => "screen#slides", :format => :json, :as => "conductor_slides"
  match 'image/:template/:image', :to => "screen#image", :as => "image_screen"
  match 'displayauth', :to => "screen#displayauth", :as => "display_authentication"
  match "screen.manifest", :to => "screen#manifest", :as => "manifest_screen"

  resources :user_sessions

  root :to => "channels#welcome"

end

parts/iivari/server/app/models/channel.rb
class Channel < OrganisationData
  has_many :slides, :order => "position"
  has_many :displays

  validates_presence_of :name
  validates_inclusion_of :slide_delay, :in => 2..600

  using_access_control

  def theme?
    (self.theme.nil? || self.theme.empty?) ? false : true
  end
end

parts/iivari/server/app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  filter_access_to :welcome, :attribute_check => false
  filter_access_to( :index, :new, :create,
                    :attribute_check => true,
                    :load_method => lambda { Channel.new(:school_id => @school.puavo_id) } )
  filter_access_to( :update, :edit, :destroy, :show,
                    :attribute_check => true )


  def welcome
    if current_user.role_symbols.include?(:organisation_owner)
      path = channels_path(@schools.first.puavo_id)
    else
      path = channels_path(current_user.admin_of_schools.first)
    end

    respond_to do |format|
      format.html { redirect_to path }
    end
  end

  # GET /channels
  # GET /channels.xml
  def index
    @channels = Channel.with_permissions_to(:show).find_all_by_school_id(@school.puavo_id)
    respond_with(@channels)
  end

  # GET /channels/1
  # GET /channels/1.xml
  def show
    @channel = Channel.with_permissions_to(:show).find(params[:id])
    respond_with(@channel)
  end

  # GET /channels/new
  # GET /channels/new.xml
  def new
    @channel = Channel.new
    @channel.slide_delay = 15

    respond_with(@channel)
  end

  # GET /channels/1/edit
  def edit
    @channel = Channel.with_permissions_to(:edit).find(params[:id])
  end

  # POST /channels
  # POST /channels.xml
  def create
    @channel = Channel.new(params[:channel])
    @channel.theme = "gold"
    @channel.school_id = @school.puavo_id
    @channel.save
    respond_with(@channel) do |format|
      format.html{ redirect_to( channel_path(@school.puavo_id, @channel) ) }
    end
  end

  # PUT /channels/1
  # PUT /channels/1.xml
  def update
    @channel = Channel.with_permissions_to(:update).find(params[:id])
    @channel.update_attributes(params[:channel])

    respond_with(@channel) do |format|
      format.html{ redirect_to( channel_path(@school.puavo_id, @channel) ) }
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.xml
  def destroy
    @channel = Channel.with_permissions_to(:destroy).find(params[:id])
    @channel.destroy
    respond_with(@channel)
  end
end

parts/iivari/server/app/helpers/channels_helper.rb
module ChannelsHelper
  def themes
    [ [t('.gold'), 'gold'], [t('.green'), 'green'], [t('.cyan'), 'cyan'] ]
  end

  def channels
    Channel.with_permissions_to(:show).find_all_by_school_id(@school.puavo_id)
  end
end

parts/iivari/server/app/views/channels/_form.html.erb
<%= simple_form_for @channel, :url => url do |f| %>
<%= f.input :name, :required => false %>
<%= f.input :slide_delay %>
<%= f.button :submit %>
-<%= t('links.or_cancel') %> <%= link_to t('links.cancel'), channels_path %>
<% end %>

parts/iivari/server/app/views/channels/_menu.html.erb
<ul id="jsddm">
  <li <%= controller_name.match(/channels|slides/) ? "class='current'" : "" %>>
  <%= link_to t('links.channels'), channels_path(@school.puavo_id) %>
  <ul class="submenu">
    <% channels.each do |channel| %>
    <li><%= link_to channel.name, channel_slides_path(@school.puavo_id, channel) %></li>
    <% end %>
  </ul>
  </li>
  <li <%= controller_name.match(/displays/) ? "class='current'" : "" %>>
    <%= link_to t('links.displays'), displays_path %>
  </li>
  <% permitted_to? :index, :school_admin_groups do %>
  <li <%= controller_name.match(/school_admin_groups/) ? "class='current'" : "" %>>
    <%= link_to t('links.admins'), school_admin_groups_path %>
  </li>
  <% end %>
</ul>

parts/iivari/server/app/views/channels/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render( :partial => 'form', :locals => { :url => channel_path(@school.puavo_id, @channel) } ) %>

<% content_for :tools do %>
<div><%= link_to t('links.show'), @channel, :class => "show" %></div>
<% end %>

parts/iivari/server/app/views/channels/index.html.erb
<h1><%= t('.title') %></h1>

<table class="channels">
  <tr>
    <th><%=  Channel.human_attribute_name(:name) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @channels.each do |channel| %>
  <tr>
    <td><%= channel.name %></td>
    <td><%= link_to t('links.slides'), channel_slides_path(@school.puavo_id, channel) %></td>
    <td><%= link_to t('links.show'), channel_path(@school.puavo_id, channel) %></td>
    <td><%= link_to t('links.edit'), edit_channel_path(@school.puavo_id, channel) %></td>
    <td><%= link_to t('links.destroy'), channel_path(@school.puavo_id, channel), :confirm => t('.confirm'), :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<% content_for :tools do %>
<div><%= link_to t('links.new_channel'), new_channel_path %></div>
<% end %>

parts/iivari/server/app/views/channels/new.html.erb
<h1><%= t('.title') %></h1>

<%= render( :partial => 'form', :locals => { :url => channels_path(@school.puavo_id) } )  %>

parts/iivari/server/app/views/channels/show.html.erb
<p>
  <b><%= Channel.human_attribute_name(:name) %>:</b>
  <%= @channel.name %>
</p>
<p>
  <b><%= Channel.human_attribute_name(:slide_delay) %>:</b>
  <%= @channel.slide_delay %>
</p>
<p>
  <b><%= Channel.human_attribute_name(:theme) %>:</b>
  <%= @channel.theme %>
</p>
<div><%= link_to t('links.back_to_channels'), channels_path %></div>


<% content_for :tools do %>
<div><%= link_to t('links.edit'), edit_channel_path(@school.puavo_id, @channel) %></div>
<% end %>