parts/iivari/server/config/routes.rb
Iivari::Application.routes.draw do
  resources :school_admin_groups, :path => ':school_id/admins' do
    collection do
      put(':group_id',
          :to => 'school_admin_groups#add_group',
          :as => 'add_group' )
      delete(':group_id',
          :to => 'school_admin_groups#delete_group',
          :as => 'delete_group' )
    end
  end
  resources :displays, :path => ':school_id/displays'

  match '/channels/welcome', :to => "channels#welcome", :as => 'welcome'
  resources :channels, :path => ':school_id/channels' do
    resources :slides do
      post :sort, :on => :collection
      member do
        put :toggle_status
        get :slide_status
      end
    end
  end

  resources :slides, :path => ':school_id/slides' do
    resources :slide_timers
  end

  match '/slides/new/:template', :to => "slides#new", :as => 'template_new_slide'

  match 'conductor', :to => "screen#conductor", :as => "conductor_screen"
  match 'slides.json', :to => "screen#slides", :format => :json, :as => "conductor_slides"
  match 'image/:template/:image', :to => "screen#image", :as => "image_screen"
  match 'displayauth', :to => "screen#displayauth", :as => "display_authentication"
  match "screen.manifest", :to => "screen#manifest", :as => "manifest_screen"

  resources :user_sessions

  root :to => "channels#welcome"

end

parts/iivari/server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset=utf-8 />
  <title>Iivari</title>
  <% theme = "gray" %>
 <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag theme+"/screen.css", :media => 'screen, projection' %>
  <%= stylesheet_link_tag theme+"/print.css", :media => 'print' %>
  <%= stylesheet_link_tag theme+"/topmenu.css" %>
  <%= stylesheet_link_tag theme+"/navmenu.css" %>
  <%= stylesheet_link_tag theme+"/iivari.css" %>
  <%= stylesheet_link_tag "smoothness/jquery-ui-1.8.6.custom.css" %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "jquery-ui.min" %>
  <%= javascript_include_tag "jquery-simple-drop-down-menu-plugin" %>
  <%= csrf_meta_tag %>
  <%= yield :javascript %>
</head>
<body>
  <% if theme =="sun_olive" %> 
  <div class="topNavContainer">
  <div class="topNavContentContainer">
  <% if current_user %>
    <ul id="top-menu-right" class="menu">
      <li><span><%= t('.logged_in_as') %></span></li>
	    <li><a href="#"><%= current_user.login %>
	    </a></li>
	    <li><%= link_to t('links.logout'), user_session_path(current_user), :method => :delete %></li>
    </ul>
    <% end %> 
    </div> 
  </div><!-- topNavContainer -->
  <% end %>
  <div class="container">
  <% if theme !="sun_olive" %>
  <ul id="top-menu" class="menu">
    <% if current_user %>
    <li><span class="sub"><%= session[:organisation].name %></span></li>
    <li><%= content_tag(:span, t('.schools'), :class => "sub") %>
    <%= schools_menu %>
    </li>
      <div id="top-menu-right">
	    <li><span><%= t('.logged_in_as') %></span></li>
      <li><a href="#"><%= current_user.login %></a></li>
      <li><%= link_to t('links.logout'), user_session_path(current_user), :method => :delete %></li>
      </div>
    <% end %>
    </ul> <!-- top-menu -->
  <% end %>
    <hr class="space" />

    <h1><%= @school.name %></h1>

    <div id="navbar_first_level">
      <div id="nav1">
	<ul>
	  <li class="page_item current_page_item">
	    <%= link_to channels_path do %>
	    <span><%= t('links.digital_signage') %></span>
	    <% end %>
	  </li>
	</ul>
      </div><!-- nav1 -->
    </div><!-- navbar_first_level -->

    <div id="navbar_second_level">&nbsp;
      <%= render :partial => "#{controller_name}/menu.html.erb" rescue nil %>
    </div><!-- navbar_second_level -->

    <hr class="space" />
  <div class="wrap">
    <div class="maincontent">
      <% if message_keys = flash.keys.select { |key| [:error, :notice, :success].include?(key) } %>
      <% message_keys.each do |key| %>
      <p class="<%= key %>">
	<%= flash[key] %>
      </p>
      <% end %>
      <% end %>
      <%= yield %>
    </div>

    <% if current_user %>
    <div class="sidebar">
      <h1><%= t('.tools') %></h1>
      <%= yield :tools %>
    </div>
    <% end %>

    <% unless yield(:sidebar_2).empty? %>
    <div class="sidebar">
      <%= yield :sidebar_2 %>
    </div>
    <% end %>

    <% unless yield(:sidebar_3).empty? %>
    <div class="sidebar">
      <%= yield :sidebar_3 %>
    </div>
   
    <% end %>
     <hr class="space" />
   </div><!-- wrap --> 

  </div> <!-- container -->
</body>
</html>

parts/iivari/server/app/views/layouts/screen.html.erb
<!DOCTYPE html>
<% if @cache == "true" %>
<html manifest="<%= manifest_screen_path( :resolution => ( params.has_key?(:resolution) ?
                                                           params[:resolution].to_s :
                                                           "") ) %>">
<% else %>
<html>
<% end %>
<head>
  <meta charset=utf-8 />
  <title>Iivari</title>

  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <%= yield %>

</body>
</html>

parts/iivari/server/app/views/layouts/slide_cyan.html.erb
<% if @slide.template != "web_page" %>
<div class="title_container">
<h1 class="title"><%= @slide.title %></h1>
</div>
<div class="tgradient0"></div>
<div class="tgradient1"></div>
<div class="tgradient2"></div>
<div class="tgradient3"></div>
<div class="tgradient4"></div>
<div class="tgradient5"></div>
<% end %>

<div class="content">
<%= yield %>
</div>

<div class="footer_container">
<div class="bgradient5"></div> 
<div class="bgradient4"></div> 
<div class="bgradient3"></div> 
<div class="bgradient2"></div> 
<div class="bgradient1"></div> 
<div class="bgradient0"></div>
</div>

parts/iivari/server/app/views/layouts/slide_gold.html.erb
<% if @slide.template == "web_page" %>

<%= yield %>

<% else %>

<div class="title_container">
<h1 class="title"><%= @slide.title %></h1>
</div>
<div class="tgradient0"></div>
<div class="tgradient1"></div>
<div class="tgradient2"></div>
<div class="tgradient3"></div>
<div class="tgradient4"></div>

<div class="content">
<%= yield %>
</div>

<% end %>

<div class="footer_container">
<div class="bgradient4"></div> 
<div class="bgradient3"></div> 
<div class="bgradient2"></div> 
<div class="bgradient1"></div> 
<div class="bgradient0"></div>
</div>

parts/iivari/server/app/views/layouts/slide_green.html.erb
<% if @slide.template != "web_page" %>
<div class="title_container">
<h1 class="title"><%= @slide.title %></h1>
</div>
<div class="tgradient0"></div>
<div class="tgradient1"></div>
<div class="tgradient2"></div>
<div class="tgradient3"></div>
<div class="tgradient4"></div>
<div class="tgradient5"></div>
<% end %>

<div class="content">
<%= yield %>
</div>

<div class="footer_container">
<div class="bgradient5"></div> 
<div class="bgradient4"></div> 
<div class="bgradient3"></div> 
<div class="bgradient2"></div> 
<div class="bgradient1"></div> 
<div class="bgradient0"></div>
</div>

parts/iivari/server/app/views/layouts/user_sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset=utf-8 />
  <title>Iivari</title>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "gray/screen.css", :media => 'screen, projection' %>
  <%= stylesheet_link_tag "gray/print.css", :media => 'print' %>
  <%= stylesheet_link_tag "gray/iivari.css" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

    <hr class="space" />
    <div class="login_container">
    <div class="login_content">
      <h1>Iivari</h1>
      <% if message_keys = flash.keys.select { |key| [:error, :notice, :success].include?(key) } %>
      <% message_keys.each do |key| %>
      <p class="<%= key %>">
	<%= flash[key] %>
      </p>
      <% end %>
      <% end %>
      <%= yield %>
    </div>
  </div>
</body>
</html>