parts/iivari/server/config/routes.rb
Iivari::Application.routes.draw do
  resources :school_admin_groups, :path => ':school_id/admins' do
    collection do
      put(':group_id',
          :to => 'school_admin_groups#add_group',
          :as => 'add_group' )
      delete(':group_id',
          :to => 'school_admin_groups#delete_group',
          :as => 'delete_group' )
    end
  end
  resources :displays, :path => ':school_id/displays'

  match '/channels/welcome', :to => "channels#welcome", :as => 'welcome'
  resources :channels, :path => ':school_id/channels' do
    resources :slides do
      post :sort, :on => :collection
      member do
        put :toggle_status
        get :slide_status
      end
    end
  end

  resources :slides, :path => ':school_id/slides' do
    resources :slide_timers
  end

  match '/slides/new/:template', :to => "slides#new", :as => 'template_new_slide'

  match 'conductor', :to => "screen#conductor", :as => "conductor_screen"
  match 'slides.json', :to => "screen#slides", :format => :json, :as => "conductor_slides"
  match 'image/:template/:image', :to => "screen#image", :as => "image_screen"
  match 'displayauth', :to => "screen#displayauth", :as => "display_authentication"
  match "screen.manifest", :to => "screen#manifest", :as => "manifest_screen"

  resources :user_sessions

  root :to => "channels#welcome"

end

parts/iivari/server/app/models/slide.rb
class Slide < OrganisationData
  belongs_to :channel
  has_many :slide_timers
  
  acts_as_list :scope => :channel

  before_save :fix_http_url, :remove_image_if_needed

  after_update :set_channel_updated_at
  after_create :set_channel_updated_at

  after_destroy :remove_image

  attr_accessor :slide_html

  using_access_control

  def school_id
    channel.school_id
  end

  def image_url(resolution)
    unless self.image.nil?
      "image/#{self.template}/#{self.image}?resolution=#{resolution}"
    end
  end

  def self.image_urls(channel, resolution)
    channel.slides.inject([]) do |result, s|
      s.image.nil? ? result : ( result.push s.image_url(resolution) )
    end
  end

  def updated_at
    self.channel.updated_at unless self.channel.nil?
  end

  def timers
    return self.slide_timers.map &:to_json
  end

  def slide_delay
    self.channel && self.channel.slide_delay ? self.channel.slide_delay : 15
  end

  protected

  def set_channel_updated_at
    self.channel.updated_at = Time.now
    self.channel.save
  end

  private

  def fix_http_url
    if self.template == "web_page"
      if self.body.match(/http[s]{0,1}:\/\//).nil?
        self.body = "http://#{self.body}"
      end
    end
  end

  # before_save
  def remove_image_if_needed
    if self.created_at? && self.image.nil? == false
      # Remove image if it is not used anywhere
      old_image_key = Slide.find(self.id).image
      if self.image != old_image_key && Slide.where(:image => old_image_key).count == 1
        image = Image.find_by_key(old_image_key)
        unless image.nil?
          image.destroy
        end
      end
    end
  end

  # after_destroy
  def remove_image
    unless self.image.nil?
      # Remove image if it is not used anywhere
      if Slide.where(:image => self.image).empty?
        image = Image.find_by_key(self.image)
        unless image.nil?
          image.destroy
        end
      end
    end
  end
end

parts/iivari/server/app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  respond_to :html, :js
  uses_tiny_mce

  before_filter :find_channel
  filter_access_to( :index, :create, :new, :sort,
                    :attribute_check => true,
                    :load_method => lambda { @channel } )
  filter_access_to( :show, :update, :edit, :destroy, :slide_status, :toggle_status,
                    :attribute_check => true )

  # GET /slides
  # GET /slides.xml
  def index
    @slides = @channel.slides
    respond_with(@slides)
  end

  # GET /slides/1
  # GET /slides/1.xml
  def show
    @slide = Slide.find(params[:id])

    respond_with(@slide)
  end

  # GET /slides/new
  # GET /slides/new.xml
  def new
    @slide = Slide.new
    @slide.template = params[:template] if params.has_key?(:template)

    @partial = params[:template] ? "form" : 'template'

    respond_with(@slide)
  end

  # GET /slides/1/edit
  def edit
    @slide = Slide.find(params[:id])
  end

  # POST /slides
  # POST /slides.xml
  def create
    @slide = Slide.new(params[:slide])
    if params[:slide][:image]
      image = Image.find_or_create(params[:slide][:image])
      @slide.image = image.key
    end
    @slide.channel_id = @channel.id
    @slide.save

    respond_with(@slide) do |format|
      format.html { redirect_to channel_slide_path(@school.puavo_id, @channel, @slide) }
    end
  end

  # PUT /slides/1
  # PUT /slides/1.xml
  def update
    @slide = Slide.find(params[:id])
    if params[:slide][:image]
      image = Image.find_or_create(params[:slide][:image])
      @slide.image = image.key
    end

    params[:slide].delete(:image)
    @slide.update_attributes(params[:slide])

    respond_with(@slide) do |format|
      format.html { redirect_to channel_slide_path(@school.puavo_id, @channel, @slide) }
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.xml
  def destroy
    @slide = Slide.find(params[:id])
    @slide.destroy
    respond_with(@slide) do |format|
      format.html { redirect_to channel_slides_path(@school.puavo_id, @channel) }
    end
  end

  def sort
    @slides = @channel.slides

    @slides.each do |slide|
      slide.position = params['slide'].index(slide.id.to_s) + 1
      slide.save
    end
    
    render :nothing => true
  end

  # GET /channels/1/slides/1/slide_status.js
  def slide_status
    @slide = Slide.find(params[:id])

    respond_with([@channel, @slide])
  end

  # PUT /channels/1/slides/1/toggle_status.js
  def toggle_status
    @slide = Slide.find(params[:id])
    @slide.toggle(:status)
    @slide.save
    
    respond_with([@channel, @slide]) do |format|
        format.js { render :action => :slide_status }
    end
  end

  private

  def find_channel
    # FIXME, find channel by screen_key
    if params[:channel_id]
      @channel = Channel.find(params[:channel_id])
    else
      @channel = Channel.first
    end
  end
end

parts/iivari/server/app/helpers/slides_helper.rb
module SlidesHelper
end

parts/iivari/server/app/views/slides/_form.html.erb
<%= form_for([@channel, @slide], :url => url, :html => { :multipart => true }) do |f| %>

<%= render :partial => "template_" + @slide.template, :locals => { :f => f } %>

<%= f.hidden_field :template, :value => @slide.template %>

<%= f.submit %>
<%= t('links.or_cancel') %> <%= link_to t('links.cancel'), channel_slides_path(@school.puavo_id, @channel) %>

<% end %>

parts/iivari/server/app/views/slides/_status.html.erb
<div
<% if @slide.status %>
 class="active">
<%= t('.slide_is_active') %>
<% else %>
 class="not_active">
<%= t('.slide_is_not_active') %>
<% end %>
</div>
<%= link_to( @slide.status ? t('links.deactive') : t('links.active'),
             toggle_status_channel_slide_path(@school.puavo_id, @channel, @slide),
	     :method => :put,
	     :remote => true,
	     :id => 'slide_status_button' ) %>

parts/iivari/server/app/views/slides/_template.html.erb
<h2><%= t('.select_slide_template') %>:</h2>

<%= link_to image_tag("only_text.png", :title => t('.link_text')), new_channel_slide_url(:template => "only_text"), :title => t('.link_text') %>
<%= link_to image_tag("right_image.png", :title => t('.link_right_image')), new_channel_slide_url(:template => "right_image"), :title => t('.link_right_image') %>
<%= link_to image_tag("left_image.png", :title => t('.link_left_image')), new_channel_slide_url(:template => "left_image"), :title => t('.link_left_image') %>
<%= link_to image_tag("only_image.png", :title => t('.link_only_image')), new_channel_slide_url(:template => "only_image"), :title => t('.link_only_image') %>
<%= link_to( image_tag("web_page.png",
             :title => t('.link_web_page')),
             new_channel_slide_url(:template => "web_page"),
             :title => t('.link_web_page') ) %>

<div><%= link_to t('links.back_to_slides'), channel_slides_path(@channel) %></div>

parts/iivari/server/app/views/slides/_template_left_image.html.erb
<div class="slide_title">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>

<div class="lefthalf">
  <%= f.file_field :image %>
  <% if @slide.image %>
  <img src="<%= root_path %>image/<%= @slide.template %>/<%= @slide.image %>?resolution=720x350" />
  <% end %>
</div>

<div class="righthalf">
  <%= f.text_area :body, :class => 'mceEditor' %>
</div>

parts/iivari/server/app/views/slides/_template_only_image.html.erb
<div class="slide_title">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>

<div class="full">
  <%= f.file_field :image %>
  <% if @slide.image %>
  <img src="<%= root_path %>image/<%= @slide.template %>/<%= @slide.image %>?resolution=720x350" />
  <% end %>
</div>

parts/iivari/server/app/views/slides/_template_only_text.html.erb
<div class="slide_title">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>

<div class="full">
  <%= f.text_area :body, :class => 'mceEditor' %>
</div>

parts/iivari/server/app/views/slides/_template_right_image.html.erb
<div class="slide_title">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>

<div class="lefthalf">
  <%= f.text_area :body, :class => 'mceEditor' %>
</div>

<div class="righthalf">
  <%= f.file_field :image %>
  <% if @slide.image %>
  <img src="<%= root_path %>image/<%= @slide.template %>/<%= @slide.image %>?resolution=720x350" />
  <% end %>
</div>

parts/iivari/server/app/views/slides/_template_web_page.html.erb
<div class="slide_title">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>

<div class="full">
  <%= f.label :body, t('.label_of_body') %><br />
  <%= f.text_field :body %>
</div>

parts/iivari/server/app/views/slides/edit.html.erb
<% content_for :javascript do %>
  <%= include_tiny_mce_if_needed :content_css => stylesheet_path("slides/editor_content") %>
<% end %>

<h1><%= t('.title') %></h1>

<div class="slide">
<%= render :partial => 'form', :locals => { :url => channel_slide_path(@school.puavo_id, @channel, @slide)} %>
</div>

<% content_for :tools do %>
<div><%= link_to t('links.show'), channel_slide_path(@school.puavo_id, @channel, @slide), :class => "show"  %></div>
<% end %>

parts/iivari/server/app/views/slides/index.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag "slides/index" %>
<% end %>

<h1><%= t('.title', :name => h(@channel.name)).html_safe %></h1>


<ul id="slides">
<% @slides.each do |slide| %>
  <li id="slide_<%= slide.id %>" class="slide_item">
    <table>
      <tr>
	<td rowspan="2" class="transform_move">
	  <span>
            <%= image_tag('transform-move.png', :title => t('.drag'), :class => "action" ) %>
	  </span>
        </td>
	<td rowspan="2">
	  <% content_tag("iframe",
                  { :style => "z-index: -1;",
                    :scrolling => "no",
                    :height => "150",
                    :width => "250",
                    :src => conductor_screen_path( :cache => "false",
                                                   :slide_id => slide.id,
                                                   :resolution => "250x150" ) } ) do %>
          <% end %>
	</td>
      
	<td class="title">
	  <%= slide.title %>
	</td>
      </tr>
      <tr>
	<td class="action">
	  <%= link_to image_tag( 'video-display.png', :title => t('links.show') ), channel_slide_path(@school.puavo_id, @channel, slide), :title => t('links.show') %>
	  <%= link_to image_tag('preferences-system.png', :title => t('links.edit') ), edit_channel_slide_path(@school.puavo_id, @channel, slide), :title => t('links.edit') %>
	  <%= link_to image_tag('edit-delete.png', :title => t('links.destroy') ), channel_slide_path(@school.puavo_id, @channel, slide), :confirm => t('.confirm'), :method => :delete, :title => t('links.destroy') %>
	</td>
      </tr>
    </table>
    <hr />
  </li>
<% end %>

</ul>

<br />

<% content_for :tools do %>
<div>
<%= link_to( t('links.preview_channel_slides'),
             conductor_screen_path( :cache => "false",
                                    :channel_id => @channel.id,
                                    :resolution => "720x405" ),
             :id => "previewSlides" )  %>
</div>
<div><%= link_to t('links.new_slides'), new_channel_slide_path %></div>
<% end %>

parts/iivari/server/app/views/slides/new.html.erb
<% content_for :javascript do %>
  <%= include_tiny_mce_if_needed :content_css => stylesheet_path("slides/editor_content") %>
<% end %>

<h1><%= t('.title') %></h1>

<%= render :partial => @partial, :locals => { :url => channel_slides_path(@school.puavo_id, @channel)} %>

parts/iivari/server/app/views/slides/show.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag "slides/show" %>
  <%= javascript_tag "var root_path = '#{root_path}#{@school.puavo_id}/'"%>
  <%= javascript_tag "var slide_id = #{@slide.id}"%>
  <%= javascript_tag "var channel_id = #{@channel.id}"%>
  <%= javascript_tag "var application_locale = '#{I18n.locale}'"%>
  <%= javascript_include_tag "datetimepicker/jquery-ui-timepicker-addon.js" %>
  <%= javascript_include_tag "datetimepicker/jquery.ui.datepicker-fi.js" %>
<% end %>

<div class="slide_navigation">
<% if @slide.first? == false %>
<%= link_to t('links.previous'), channel_slide_path(@school.puavo_id, @channel, @slide.higher_item) %>
<% end %>

<%= if @slide.first? == false && @slide.last? == false then " - " end %> 

<% if @slide.last? == false %>
       <%= link_to t('links.next'), channel_slide_path(@school.puavo_id, @channel, @slide.lower_item) %>
<% end %>
<%= "(#{@slide.position}/#{@channel.slides.count})" %>
</div>

<div>
<% content_tag("iframe",
               { :class => "slide_show",
                 :scrolling => "no",
                 :height => "400",
                 :width => "650",
                 :src => conductor_screen_path( :cache => "false",
                                                :slide_id => @slide.id,
                                                :resolution => "650x400" ) } ) do %>
<% end %>
</div>

<% if @slide.slide_timers.empty? %>
<h2><%= link_to t('links.slide_timers'), slide_slide_timers_path(@school.puavo_id, @slide), :remote => true, :class => 'link_slide_timers' %></h2>
<% else %>
<h2><%= t('links.slide_timers') %></h2>
<% end %>
<div class="slide_timers">

</div>

<% content_for :tools do %>
<div><%= link_to t('links.edit'), edit_channel_slide_path(@school.puavo_id, @channel, @slide) %></div>
<div>
<%= link_to( t('links.destroy'),
 channel_slide_path(@school.puavo_id, @channel, @slide),
 :confirm => t('.confirm'),
 :method => :delete ) %>
</div>
<div><%= link_to t('links.slides'), channel_slides_path %></div>
<% end %>

<% content_for :sidebar_2 do %>
<h1><%= t('.status_title') %></h1>
<p id="slide_status">
</p>

<% end %>

parts/iivari/server/app/views/slides/slide_status.js.erb
$('#slide_status').html("<%= escape_javascript( render :partial => 'status' ) %>");
$('#slide_status_button').button();