parts/iivari/server/config/routes.rb
Iivari::Application.routes.draw do
  resources :school_admin_groups, :path => ':school_id/admins' do
    collection do
      put(':group_id',
          :to => 'school_admin_groups#add_group',
          :as => 'add_group' )
      delete(':group_id',
          :to => 'school_admin_groups#delete_group',
          :as => 'delete_group' )
    end
  end
  resources :displays, :path => ':school_id/displays'

  match '/channels/welcome', :to => "channels#welcome", :as => 'welcome'
  resources :channels, :path => ':school_id/channels' do
    resources :slides do
      post :sort, :on => :collection
      member do
        put :toggle_status
        get :slide_status
      end
    end
  end

  resources :slides, :path => ':school_id/slides' do
    resources :slide_timers
  end

  match '/slides/new/:template', :to => "slides#new", :as => 'template_new_slide'

  match 'conductor', :to => "screen#conductor", :as => "conductor_screen"
  match 'slides.json', :to => "screen#slides", :format => :json, :as => "conductor_slides"
  match 'image/:template/:image', :to => "screen#image", :as => "image_screen"
  match 'displayauth', :to => "screen#displayauth", :as => "display_authentication"
  match "screen.manifest", :to => "screen#manifest", :as => "manifest_screen"

  resources :user_sessions

  root :to => "channels#welcome"

end

parts/iivari/server/app/models/slide_timer.rb
class SlideTimer < ActiveRecord::Base
  belongs_to :slide

  after_update :set_channel_updated_at
  after_create :set_channel_updated_at
  after_update :set_channel_updated_at
  before_destroy :set_channel_updated_at

  def school_id
    slide.channel.school_id
  end

  def to_json
    {
      "start_datetime" => json_datetime(self.start_datetime),
      "end_datetime" => json_datetime(self.end_datetime),
      "start_time" => json_datetime(self.start_time),
      "end_time" => json_datetime(self.end_time),
      "weekday_0" => self.weekday_0,
      "weekday_1" => self.weekday_1,
      "weekday_2" => self.weekday_2,
      "weekday_3" => self.weekday_3,
      "weekday_4" => self.weekday_4,
      "weekday_5" => self.weekday_5,
      "weekday_6" => self.weekday_6
    }
  end

  private
  
  # formats the datetime for WebKit JavaScriptCore
  def json_datetime(datetime)
    datetime.getutc.strftime('%Y/%m/%d %H:%M GMT+0000') rescue ""
  end

  def set_channel_updated_at
    self.slide.channel.updated_at = Time.now
    self.slide.channel.save
  end
end

parts/iivari/server/app/controllers/slide_timers_controller.rb
class SlideTimersController < ApplicationController
  before_filter :find_slide
  respond_to :html, :json
  filter_access_to( :index, :create, :new,
                    :attribute_check => true,
                    :load_method => lambda { @slide.channel } )
  filter_access_to( :show, :update, :edit, :destroy,
                    :attribute_check => true )

  # GET /slide_timers
  # GET /slide_timers.xml
  def index
    @slide_timers = SlideTimer.where(:slide_id => @slide.id)
    @slide_timer = SlideTimer.new

    respond_with(@slide_timers) do |format|
      format.html 
      format.js
    end
  end

  # GET /slide_timers/1
  # GET /slide_timers/1.xml
  def show
    @slide_timer = SlideTimer.find(params[:id])
    respond_with(@slide_timer)
  end

  # GET /slide_timers/new
  # GET /slide_timers/new.xml
  def new
    @slide_timer = SlideTimer.new

    respond_with(@slide_timer)
  end

  # GET /slide_timers/1/edit
  def edit
    @slide_timer = SlideTimer.find(params[:id])
  end

  # POST /slide_timers
  # POST /slide_timers.xml
  def create
    @slide_timer = SlideTimer.new(params[:slide_timer])
    @slide_timer.slide_id = @slide.id
    @slide_timer.save
    respond_with([@slide, @slide_timer]) do |format|
      format.js { redirect_to slide_slide_timers_path(@school.puavo_id, @slide, :format => :js) }
    end
  end

  # PUT /slide_timers/1
  # PUT /slide_timers/1.xml
  def update
    @slide_timer = SlideTimer.find(params[:id])
    @slide_timer.update_attributes(params[:slide_timer])
    respond_with([@slide, @slide_timer])
  end

  # DELETE /slide_timers/1
  # DELETE /slide_timers/1.xml
  def destroy
    @slide_timer = SlideTimer.find(params[:id])
    @slide_timer.destroy
    respond_with([@slide, @slide_timer]) do |format|
      format.js { render :nothing => true }  
    end
  end

  private

  def find_slide
    @slide = Slide.find(params[:slide_id])
  end
end

parts/iivari/server/app/helpers/slide_timers_helper.rb
module SlideTimersHelper
end

parts/iivari/server/app/views/slide_timers/_form.html.erb
<tr class="form">
  <td><%= f.text_field :start_datetime, :size => '15' %></td>
  <td><%= f.text_field :end_datetime, :size => '15' %></td>
  <td><%= f.text_field :start_time, :size => '6', :value => I18n.l(Time.local(0)) %></td>
  <td><%= f.text_field :end_time, :size => '6', :value => I18n.l(Time.local(0) + 23.hours + 59.minutes) %></td>
</tr>
<tr><td colspan="4">
<table align="right">
<tr>
      <th><%= SlideTimer.human_attribute_name :weekday_1 %></th>
      <th><%= SlideTimer.human_attribute_name :weekday_2 %></th>
      <th><%= SlideTimer.human_attribute_name :weekday_3 %></th>
      <th><%= SlideTimer.human_attribute_name :weekday_4 %></th>
      <th><%= SlideTimer.human_attribute_name :weekday_5 %></th>
      <th><%= SlideTimer.human_attribute_name :weekday_6 %></th>
      <th><%= SlideTimer.human_attribute_name :weekday_0 %></th>
</tr>
<tr>
      <td><%= f.check_box :weekday_1 %></td>
      <td><%= f.check_box :weekday_2 %></td>
      <td><%= f.check_box :weekday_3 %></td>
      <td><%= f.check_box :weekday_4 %></td>
      <td><%= f.check_box :weekday_5 %></td>
      <td><%= f.check_box :weekday_6 %></td>
      <td><%= f.check_box :weekday_0 %></td>
</tr>
</table>
</td></tr>
<tr>
    <td colspan="2"><%= f.submit %></td>
</tr>

parts/iivari/server/app/views/slide_timers/_list.html.erb
<%= form_for(@slide_timer, :url => slide_slide_timers_path(@school.puavo_id, @slide), :remote => true) do |f| %>
<table class="table_slide_timers">
  <tr>
    <th><%= SlideTimer.human_attribute_name :start_datetime %></th>
    <th><%= SlideTimer.human_attribute_name :end_datetime %></th>
    <th><%= SlideTimer.human_attribute_name :start_time %></th>
    <th><%= SlideTimer.human_attribute_name :end_time %></th>
  </tr>

<% @slide_timers.each do |slide_timer| %>
<tr class="timer">
  <td><%= l(slide_timer.start_datetime, :format => :datetime) rescue t('.empty') %></td>
  <td><%= l(slide_timer.end_datetime, :format => :datetime) rescue t('.empty') %></td>
  <td><%= l(slide_timer.start_time) %></td>
  <td><%= l(slide_timer.end_time) %></td>
  <td rowspan="2" class="td_delete_timer" width="48">
    <%= link_to image_tag( 'edit-delete.png', :title => t('links.destroy') ),
                           slide_slide_timer_path(@school.puavo_id, @slide, slide_timer),
                           :confirm => t('confirm'),
                           :method => :delete,
                           :remote => true,
                           :class => "delete_timer" %>
  </td>
</tr>
<tr class="weekday_and_action">
  <td></td>
  <td></td>
  <td colspan="2">
  <table>
    <tr>
      <th><%= SlideTimer.human_attribute_name :weekday_1 %></th>
      <th><%= SlideTimer.human_attribute_name :weekday_2 %></th>
      <th><%= SlideTimer.human_attribute_name :weekday_3 %></th>
      <th><%= SlideTimer.human_attribute_name :weekday_4 %></th>
      <th><%= SlideTimer.human_attribute_name :weekday_5 %></th>
      <th><%= SlideTimer.human_attribute_name :weekday_6 %></th>
      <th><%= SlideTimer.human_attribute_name :weekday_0 %></th>
    </tr>
    <tr>
      <td><%= slide_timer.weekday_1 ? "X" : "" %></td>
      <td><%= slide_timer.weekday_2 ? "X" : "" %></td>
      <td><%= slide_timer.weekday_3 ? "X" : "" %></td>
      <td><%= slide_timer.weekday_4 ? "X" : "" %></td>
      <td><%= slide_timer.weekday_5 ? "X" : "" %></td>
      <td><%= slide_timer.weekday_6 ? "X" : "" %></td>
      <td><%= slide_timer.weekday_0 ? "X" : "" %></td>
    </tr>
  </table>
</td></tr>

<% end %>

<%= render :partial => 'form', :locals => { :f => f } %>
</table>
<% end %>

parts/iivari/server/app/views/slide_timers/edit.html.erb
<h1>Editing slide_timer</h1>

<%= render 'form' %>

<%= link_to 'Show', slide_slide_timer_path(@slide, @slide_timer) %> |
<%= link_to 'Back', slide_slide_timers_path(@slide) %>

parts/iivari/server/app/views/slide_timers/index.html.erb
<h1>Listing slide_timers</h1>

<table>
  <tr>
    <th>Start datetime</th>
    <th>End datetime</th>
    <th>Start time</th>
    <th>End time</th>
    <th>Slide</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @slide_timers.each do |slide_timer| %>
  <tr>
    <td><%= slide_timer.start_datetime %></td>
    <td><%= slide_timer.end_datetime %></td>
    <td><%= slide_timer.start_time %></td>
    <td><%= slide_timer.end_time %></td>
    <td><%= slide_timer.slide_id %></td>
    <td><%= link_to 'Show', slide_slide_timer_path(@slide, slide_timer) %></td>
    <td><%= link_to 'Edit', edit_slide_slide_timer_path(@slide, slide_timer) %></td>
    <td><%= link_to 'Destroy', slide_slide_timer_path(@slide, slide_timer), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Slide timer', new_slide_slide_timer_path(@slide) %>

parts/iivari/server/app/views/slide_timers/index.js.erb
$('.slide_timers').html("<%= escape_javascript( render :partial => 'list' ) %>");
setTimerListEvent();

parts/iivari/server/app/views/slide_timers/new.html.erb
<h1>New slide_timer</h1>

<%= render 'form' %>

<%= link_to 'Back', slide_slide_timers_path(@slide) %>

parts/iivari/server/app/views/slide_timers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start datetime:</b>
  <%= @slide_timer.start_datetime %>
</p>

<p>
  <b>End datetime:</b>
  <%= @slide_timer.end_datetime %>
</p>

<p>
  <b>Start time:</b>
  <%= @slide_timer.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @slide_timer.end_time %>
</p>

<p>
  <b>Slide:</b>
  <%= @slide_timer.slide_id %>
</p>


<%= link_to 'Edit', edit_slide_slide_timer_path(@slide, @slide_timer) %> |
<%= link_to 'Back', slide_slide_timers_path(@slide) %>